(() => {
  const MODEL_KEY = 'wavepoint-page-model-v1';
  const PAGE = 'index.html';
  const zoneDefinitions = [
    { id: 'hero', label: 'Hero', type: 'fixed', allowed: ['hero'], min: 1, max: 1 },
    { id: 'allies', label: 'Aliados', type: 'repeatable', allowed: ['partner-card'], min: 3, max: 12 },
    { id: 'cameras', label: 'Cámaras', type: 'repeatable', allowed: ['camera-card'], min: 1, max: 6 },
    { id: 'services', label: 'Servicios', type: 'repeatable', allowed: ['service-card'], min: 3, max: 12 },
    { id: 'guide', label: 'Guía local', type: 'repeatable', allowed: ['image-text'], min: 1, max: 4 },
    { id: 'about', label: 'Nosotros', type: 'repeatable', allowed: ['image-text'], min: 1, max: 3 },
    { id: 'newsletter', label: 'Newsletter', type: 'fixed', allowed: ['newsletter'], min: 1, max: 1 }
  ];
  const blockTemplates = {
    hero: { label: 'Hero', fields: ['title', 'description', 'image'] },
    'partner-card': { label: 'Aliado', fields: ['name', 'location', 'description', 'image', 'link'] },
    'camera-card': { label: 'Cámara', fields: ['name', 'location', 'description', 'image', 'link'] },
    'service-card': { label: 'Servicio', fields: ['title', 'description', 'image', 'link'] },
    'image-text': { label: 'Imagen + texto', fields: ['title', 'description', 'image', 'link'] },
    newsletter: { label: 'Newsletter', fields: ['title', 'description'] }
  };
  const initial = {
    page: PAGE,
    zones: {
      hero: [{ id: 'hero-1', type: 'hero', title: { es: 'A través de quienes lo llaman hogar', en: 'Through those who call it home' }, description: { es: 'WavePoint te conecta con las mejores experiencias en Tamarindo.', en: 'WavePoint connects you with the best experiences in Tamarindo.' }, image: 'assets/img/site/home-hero.jpg' }],
      allies: [{ id: 'ally-1', type: 'partner-card', name: { es: 'Chop House', en: 'Chop House' }, location: { es: 'Tamarindo', en: 'Tamarindo' }, image: 'assets/img/collaborators/chop-house/after-hours.jpeg', link: 'https://chophouse.cr/' }, { id: 'ally-2', type: 'partner-card', name: { es: 'Capitán Suizo', en: 'Capitán Suizo' }, location: { es: 'Tamarindo', en: 'Tamarindo' }, image: 'assets/img/stays/capitan-suizo/cover.jpg', link: 'Enlaces/capitan-suizo.html' }, { id: 'ally-3', type: 'partner-card', name: { es: 'Casa de Maderas', en: 'Casa de Maderas' }, location: { es: 'Palm Beach', en: 'Palm Beach' }, image: 'assets/img/stays/casa-maderas/cover.jpg', link: 'Enlaces/casa-maderas.html' }],
      cameras: [{ id: 'camera-1', type: 'camera-card', name: { es: 'Capitán Suizo', en: 'Capitán Suizo' }, location: { es: 'Tamarindo', en: 'Tamarindo' }, description: { es: 'Condiciones en vivo del spot.', en: 'Live spot conditions.' }, image: 'assets/img/stays/capitan-suizo/beach.jpg', link: 'Enlaces/capitan-suizo.html' }],
      services: [{ id: 'service-1', type: 'service-card', title: { es: 'Clases de surf', en: 'Surf lessons' }, description: { es: 'Clases para todos los niveles.', en: 'Lessons for all levels.' }, image: 'assets/img/services/surf-lessons/surf-lesson-woman.webp', link: 'service-detail.html?id=surf-lessons' }, { id: 'service-2', type: 'service-card', title: { es: 'Surf coaching', en: 'Surf coaching' }, description: { es: 'Entrenamiento personalizado.', en: 'Personalized coaching.' }, image: 'assets/img/services/surf-coaching/surf-coaching-session.jpg', link: 'service-detail.html?id=surf-coaching' }, { id: 'service-3', type: 'service-card', title: { es: 'Roca Bruja', en: "Witch's Rock" }, description: { es: 'Un día de surf en barco.', en: 'A surf day by boat.' }, image: 'assets/img/services/witchs-rock/witch-rock-surf-trip.webp', link: 'service-detail.html?id=witch-rock' }],
      guide: [{ id: 'guide-1', type: 'image-text', title: { es: 'Vive Tamarindo', en: 'Live Tamarindo' }, description: { es: 'Playas, experiencias y guía local.', en: 'Beaches, experiences and local guidance.' }, image: 'assets/img/guide/after-guide.jpg', link: 'guia-playas.html' }],
      about: [{ id: 'about-1', type: 'image-text', title: { es: 'Una herramienta hecha por surfistas.', en: 'A tool made by surfers.' }, description: { es: 'WavePoint conecta a locales y visitantes.', en: 'WavePoint connects locals and visitors.' }, image: 'assets/img/site/backgrounds/camaras.jpg', link: '#nosotros' }],
      newsletter: [{ id: 'newsletter-1', type: 'newsletter', title: { es: 'Entérate primero', en: 'Stay in the loop' }, description: { es: 'Recibe novedades y promociones seleccionadas.', en: 'Receive selected updates and promotions.' } }]
    }
  };
  const state = { model: readModel(), zone: 'hero', block: null, lang: 'es' };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  function readModel() { try { const value = JSON.parse(localStorage.getItem(MODEL_KEY) || 'null'); return value?.zones ? value : structuredClone(initial); } catch (_) { return structuredClone(initial); } }
  function saveModel() { localStorage.setItem(MODEL_KEY, JSON.stringify(state.model)); }
  function definition() { return zoneDefinitions.find((item) => item.id === state.zone); }
  function blocks() { return state.model.zones[state.zone] || []; }
  function selected() { return blocks().find((item) => item.id === state.block); }
  function labelFor(block) { const template = blockTemplates[block.type]; return block[template?.fields[0]]?.[state.lang] || template?.label || 'Bloque'; }
  function show() { const editor = $('editorView'); if (!editor || editor.hidden) return; renderZones(); renderBlocks(); renderInspector(); }
  function renderZones() { $('zoneList').innerHTML = zoneDefinitions.map((zone) => `<button type="button" class="zone-item ${zone.id === state.zone ? 'active' : ''}" data-zone="${zone.id}"><span>${esc(zone.label)}</span><small>${state.model.zones[zone.id]?.length || 0}/${zone.max}</small></button>`).join(''); $('zoneList').querySelectorAll('[data-zone]').forEach((button) => button.addEventListener('click', () => { state.zone = button.dataset.zone; state.block = null; show(); })); }
  function renderBlocks() { const def = definition(); const items = blocks(); $('selectedZoneTitle').textContent = def.label; $('zoneCount').textContent = `${items.length}/${def.max}`; $('blockList').innerHTML = items.map((block, index) => `<div class="block-row ${block.id === state.block ? 'active' : ''}"><button class="block-select" type="button" data-block="${block.id}"><span class="drag-handle">⋮⋮</span><span><strong>${esc(labelFor(block))}</strong><small>${esc(blockTemplates[block.type].label)}</small></span></button><div class="block-actions"><button type="button" data-move="up" data-id="${block.id}" ${index === 0 ? 'disabled' : ''}>↑</button><button type="button" data-move="down" data-id="${block.id}" ${index === items.length - 1 ? 'disabled' : ''}>↓</button></div></div>`).join('') || '<p class="empty">Esta zona no tiene bloques.</p>'; $('blockList').querySelectorAll('[data-block]').forEach((button) => button.addEventListener('click', () => { state.block = button.dataset.block; renderBlocks(); renderInspector(); })); $('blockList').querySelectorAll('[data-move]').forEach((button) => button.addEventListener('click', () => moveBlock(button.dataset.id, button.dataset.move))); $('addBlockButton').disabled = def.type === 'fixed' || items.length >= def.max; }
  function renderInspector() { const block = selected(); if (!block) { $('blockInspector').innerHTML = '<p class="empty">Seleccioná un bloque para editar sus propiedades.</p>'; return; } const fields = blockTemplates[block.type].fields; $('blockInspector').innerHTML = `<div class="inspector-head"><p class="sidebar-label">PROPIEDADES</p><button class="danger tiny" id="deleteBlock" type="button" ${blocks().length <= definition().min ? 'disabled' : ''}>Eliminar</button></div>${fields.map((field) => { const value = block[field]?.[state.lang] ?? block[field] ?? ''; const bilingual = ['title','description','name','location'].includes(field); return `<label class="inspector-field">${esc(fieldLabel(field))}${bilingual ? '' : ''}${bilingual ? `<textarea data-prop="${field}">${esc(value)}</textarea>` : `<input data-prop="${field}" value="${esc(value)}" />`}</label>`; }).join('')}<div class="inspector-tools"><button class="secondary tiny" id="duplicateBlock" type="button" ${blocks().length >= definition().max ? 'disabled' : ''}>Duplicar</button><span class="muted tiny-copy">Idioma: ${state.lang.toUpperCase()}</span></div>`; $('blockInspector').querySelectorAll('[data-prop]').forEach((field) => field.addEventListener('input', () => { const key = field.dataset.prop; if (typeof block[key] === 'object') block[key][state.lang] = field.value; else block[key] = field.value; renderBlocks(); saveModel(); })); $('deleteBlock').addEventListener('click', () => deleteBlock()); $('duplicateBlock').addEventListener('click', () => duplicateBlock()); }
  function fieldLabel(field) { return ({ title:'Título', description:'Descripción', name:'Nombre', location:'Ubicación', image:'Imagen', link:'Enlace' }[field] || field); }
  function newBlock(type) { const fields = blockTemplates[type].fields; const block = { id: `${type}-${Date.now()}`, type }; fields.forEach((field) => { block[field] = ['title','description','name','location'].includes(field) ? { es: `Nuevo ${field}`, en: `New ${field}` } : ''; }); return block; }
  function addBlock() { const def = definition(); if (def.type === 'fixed' || blocks().length >= def.max) return; const block = newBlock(def.allowed[0]); state.model.zones[state.zone].push(block); state.block = block.id; saveModel(); show(); }
  function deleteBlock() { if (blocks().length <= definition().min) return; if (!confirm('¿Quitar este bloque? Podés restaurarlo desde el JSON original.')) return; state.model.zones[state.zone] = blocks().filter((item) => item.id !== state.block); state.block = null; saveModel(); show(); }
  function duplicateBlock() { const block = selected(); const def = definition(); if (!block || blocks().length >= def.max) return; const copy = structuredClone(block); copy.id = `${block.type}-${Date.now()}`; state.model.zones[state.zone].splice(blocks().indexOf(block) + 1, 0, copy); state.block = copy.id; saveModel(); show(); }
  function moveBlock(id, direction) { const list = blocks(); const index = list.findIndex((item) => item.id === id); const next = direction === 'up' ? index - 1 : index + 1; if (index < 0 || next < 0 || next >= list.length) return; [list[index], list[next]] = [list[next], list[index]]; saveModel(); renderBlocks(); }
  function exportModel() { const blob = new Blob([JSON.stringify(state.model, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `wavepoint-page-model-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(link.href); }
  function resetModel() { if (!confirm('¿Restaurar las zonas y bloques originales?')) return; state.model = structuredClone(initial); state.block = null; saveModel(); show(); }
  function init() { $('visualPageSelect').addEventListener('change', (event) => { $('sitePreview').src = event.target.value; state.model.page = event.target.value; }); $('addBlockButton').addEventListener('click', addBlock); $('visualPageSelect').value = state.model.page || PAGE; document.addEventListener('click', (event) => { const tab = event.target.closest('[data-lang]'); if (tab) { state.lang = tab.dataset.lang; show(); } }); $('exportModelButton').addEventListener('click', exportModel); $('resetModelButton').addEventListener('click', resetModel); const observer = new MutationObserver(show); observer.observe($('editorView'), { attributes: true, attributeFilter: ['hidden'] }); show(); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
})();
